// GET VIDEOS
export const GET_ALL_VIDEOS = 'GET_ALL_VIDEOS';
export const RECEIVED_ALL_VIDEOS = 'RECEIVED_ALL_VIDEOS';
export const RECEIVED_ALL_VIDEOS_FAILED = 'RECEIVED_ALL_VIDEOS_FAILED';

export const GET_ALL_VIDEO_IS_LIVESTREAM = 'GET_ALL_VIDEO_IS_LIVESTREAM';
export const RECEIVED_ALL_VIDEO_IS_LIVESTREAM = 'RECEIVED_ALL_VIDEO_IS_LIVESTREAM';
export const RECEIVED_ALL_VIDEO_IS_LIVESTREAM_FAILED = 'RECEIVED_ALL_VIDEO_IS_LIVESTREAM_FAILED';

export const GET_ALL_VIDEO_IS_ALREADY_LIVESTREAM = 'GET_ALL_VIDEO_IS_ALREADY_LIVESTREAM';
export const RECEIVED_ALL_VIDEO_IS_ALREADY_LIVESTREAM = 'RECEIVED_ALL_VIDEO_IS_ALREADY_LIVESTREAM';
export const RECEIVED_ALL_VIDEO_IS_ALREADY_LIVESTREAM_FAILED = 'RECEIVED_ALL_VIDEO_IS_ALREADY_LIVESTREAM_FAILED';

export const GET_ALL_VIDEO_WILL_BE_LIVESTREAM = 'GET_ALL_VIDEO_WILL_BE_LIVESTREAM';
export const RECEIVED_ALL_VIDEO_WILL_BE_LIVESTREAM = 'RECEIVED_ALL_VIDEO_WILL_BE_LIVESTREAM';
export const RECEIVED_ALL_VIDEO_WILL_BE_LIVESTREAM_FAILED = 'RECEIVED_ALL_VIDEO_WILL_BE_LIVESTREAM_FAILED';

// GET STREAM
export const GET_STREAM = 'GET_STREAM';
export const RECEIVED_STREAM_SUCCESS = 'RECEIVED_STREAM_SUCCESS';
export const RECEIVED_STREAM_FAILED = 'RECEIVED_STREAM_FAILED';

// GET CHANNELS
export const GET_ALL_CHANNELS = 'GET_ALL_CHANNELS';
export const GET_PUBLIC_CHANNELS = 'GET_PUBLIC_CHANNELS';
export const GET_PRIVATE_CHANNELS = 'GET_PRIVATE_CHANNELS';

// GET VIDEOS IS LIVE
export const GET_PUBLIC_LIVE_VIDEOS = 'GET_PUBLIC_LIVE_VIDEOS';
export const GET_PRIVATE_LIVE_VIDEOS = 'GET_PRIVATE_LIVE_VIDEOS';

// GET VIDEOS ALREADY RECORED
export const GET_PUBLIC_RECORED_VIDEOS = 'GET_PUBLIC_RECORED_VIDEOS';
export const GET_PRIVATE_RECORED_VIDEOS = 'GET_PRIVATE_RECORED_VIDEOS';

// GET FAVORITE CHANNELS
export const GET_FAVORITE_CHANNELS = 'GET_FAVORITE_CHANNELS';
export const GET_FAVORITE_VIDEOS = 'GET_FAVORITE_VIDEOS';

// REQUEST RESET PASSWORD
export const REQUEST_RESET_PASSWORD_START = 'REQUEST_RESET_PASSWORD_START';
export const REQUEST_RESET_PASSWORD_SUCCESS = 'REQUEST_RESET_PASSWORD_SUCCESS';
export const REQUEST_RESET_PASSWORD_FALIED = 'REQUEST_RESET_PASSWORD_FALIED';

// USERS
export const USER_LOGIN = 'USER_LOGIN';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_AVATAR = 'UPDATE_USER_AVATAR';
export const RECEIVED_USER_DATA = 'RECEIVED_USER_DATA';
export const RECEIVED_USER_DATA_FAILED = 'RECEIVED_USER_DATA_FAILED';

// REQUEST UPDATE PROFILE
export const REQUEST_UPDATE_PROFILE_START = 'REQUEST_UPDATE_PROFILE_START';
export const REQUEST_UPDATE_PROFILE_SUCCESS = 'REQUEST_UPDATE_PROFILE_SUCCESS';
export const REQUEST_UPDATE_PROFILE_FAILED = 'REQUEST_UPDATE_PROFILE_FAILED';

// REQUEST UPDATE PASSWORD
export const REQUEST_UPDATE_PASSWORD_START = 'REQUEST_UPDATE_PASSWORD_START';
export const REQUEST_UPDATE_PASSWORD_SUCCESS = 'REQUEST_UPDATE_PASSWORD_SUCCESS';
export const REQUEST_UPDATE_PASSWORD_FAILED = 'REQUEST_UPDATE_PASSWORD_FAILED';

// CONNECTING TO STREAMING SERVER
export const CHANNEL_CONNECTING = 'CHANNEL_CONNECTING';
export const CHANNEL_CONNECTED = 'CHANNEL_CONNECTED';
export const CHANNEL_DISCONNECTED = 'CHANNEL_DISCONNECTED';

// CHATTING
export const OPEN_CHAT_PANEL = 'OPEN_CHAT_PANEL';
export const CLOSE_CHAT_PANEL = 'CLOSE_CHAT_PANEL';

// CHATTING
export const SET_SCREEN_NAME = 'SET_SCREEN_NAME';
export const GET_SCREEN_NAME = 'GET_SCREEN_NAME';

// MAP
export const OPEN_PREVIEW_PROFILE_MODAL = 'OPEN_PREVIEW_PROFILE_MODAL';
export const CLOSE_PREVIEW_PROFILE_MODAL = 'CLOSE_PREVIEW_PROFILE_MODAL';

// LOGIN
export const LOGIN_APP = 'LOGIN_APP';
export const LOGOUT_APP = 'LOGOUT_APP';

// SCREENS
export const SCREEN_PORTRAIT = 'SCREEN_PORTRAIT';
export const SCREEN_LANSCAPE = 'SCREEN_LANSCAPE';

// VIDEO CONTROLS
export const OPEN_VIDEO_CONTROLS = 'OPEN_VIDEO_CONTROLS';
export const CLOSE_VIDEO_CONTROLS = 'CLOSE_VIDEO_CONTROLS';