export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const USER_LOGIN = 'USER_LOGIN';
export const RECEIVED_USER_DATA = 'RECEIVED_USER_DATA';
export const RECEIVED_USER_DATA_FAILED = 'RECEIVED_USER_DATA_FAILED';